### ISSUE TITLE
路由器运行时返回ip地址错误

### ISSUE THREAD

**Issue by annyguoguo** [robertying/tunet-c#1]
编译在openwrt上运行，返回以下错误：
E2833: Your IP address is not in the dhcp table. Maybe you need to renew the IP address.
请问如何解决，麻烦大佬有时间看一下～

**Comment by minnyres** [comment]
在OpenSUSE上也无法联网，auth4连接出错

**Comment by minnyres** [comment]
@annyguoguo  新版本v4.0可用

**Comment by robertying** [comment]
Fixed via https://github.com/robertying/tunet-c/commit/8b4f9fcca9953bda2dd78406e58ba204e6a4d8ed

4.0.0 应该就好了
